export const QUERY_KEYS = {
  crew: () => ["/api/crew"] as const,
  crewInvites: () => ["/api/crew-invites"] as const,
  crewMemberInvites: (crewMemberId: string) => ["/api/crew", crewMemberId, "invites"] as const,

  jobs: () => ["/api/jobs"] as const,
  job: (id: string | number) => ["/api/jobs", id] as const,
  jobsUsage: () => ["/api/jobs/usage"] as const,
  jobDepositStatus: (id: string | number) => ["/api/jobs", id, "deposit-status"] as const,
  jobResolutionRequired: (id: string | number) => ["/api/jobs", id, "resolution-required"] as const,
  jobCrewInvites: (jobId: string | number) => ["/api/jobs", jobId, "crew-invites"] as const,
  jobCrewMessages: (jobId: string | number) => ["/api/jobs", jobId, "crew-messages"] as const,
  jobCrewPhotos: (jobId: string | number) => ["/api/jobs", jobId, "crew-photos"] as const,
  jobScheduledMessages: (jobId: string | number) => ["/api/jobs", jobId, "scheduled-messages"] as const,
  photoAssets: (type: string, id: string | number) => ["/api/photo-assets", type, id] as const,

  leads: Object.assign(() => ["/api/leads"] as const, {
    detail: (id: string | number) => ["/api/leads", id] as const,
    sms: (phone: string) => ["/api/sms/conversation", phone] as const,
  }),
  leadSmsMessages: (leadId: string | number) => ["/api/leads", leadId, "sms-messages"] as const,
  leadEmails: (leadId: string | number) => ["/api/leads", leadId, "emails"] as const,
  leadsFollowUp: () => ["/api/leads/follow-up-needed"] as const,
  leadPriceConfirmation: (id: string | number) => ["/api/leads", id, "active-price-confirmation"] as const,

  invoices: Object.assign(() => ["/api/invoices"] as const, {
    detail: (id: string | number) => ["/api/invoices", id] as const,
  }),
  messaging: {
    inbox: () => ["/api/sms/conversations"] as const,
  },

  payments: () => ["/api/payments"] as const,
  paymentMethods: () => ["/api/payment-methods"] as const,

  settings: () => ["/api/settings"] as const,
  services: () => ["/api/services"] as const,

  profile: () => ["/api/profile"] as const,
  authUser: () => ["/api/auth/user"] as const,
  subscriptionStatus: () => ["/api/subscription/status"] as const,
  capabilities: () => ["/api/capabilities"] as const,
  onboarding: () => ["/api/onboarding"] as const,
  activation: () => ["/api/activation"] as const,

  nudges: () => ["/api/nudges"] as const,
  moneyPlan: () => ["/api/money-plan"] as const,
  actionQueue: () => ["/api/action-queue"] as const,
  readyActions: () => ["/api/ready-actions"] as const,
  readyActionsEntity: (entityType: string, entityId: string | number) => ["/api/ready-actions/entity", entityType, entityId] as const,
  nextActionsEntity: (entityType: string, entityId: string | number) => ["/api/next-actions/entity", entityType, entityId] as const,
  nextActions: () => ["/api/next-actions"] as const,
  stallDetections: () => ["/api/stall-detections"] as const,

  bookingLink: () => ["/api/booking/link"] as const,
  bookingRequests: () => ["/api/booking-requests"] as const,
  bookingsByToken: (token: string) => ["/api/bookings/by-token", token] as const,
  bookingDetail: (token: string) => ["/api/bookings/by-token", token, "detail"] as const,
  bookingPaymentMethods: (token: string) => ["/api/bookings/by-token", token, "payment-methods"] as const,

  messages: () => ["/api/messages"] as const,
  messagesUsage: () => ["/api/messages/usage"] as const,
  smsUnreadCount: () => ["/api/sms/unread-count"] as const,
  scheduledMessages: () => ["/api/scheduled-messages"] as const,
  smsRateLimitedRecent: () => ["/api/sms/rate-limited-recent"] as const,
  smsRateLimitStatus: () => ["/api/sms/rate-limit-status"] as const,

  reviews: () => ["/api/reviews"] as const,
  reminders: () => ["/api/reminders"] as const,
  referrals: () => ["/api/referrals"] as const,
  campaigns: () => ["/api/campaigns"] as const,
  campaignSuggestions: () => ["/api/notification-campaigns/suggestions"] as const,

  billingInvoices: () => ["/api/billing/invoices"] as const,
  impact: () => ["/api/impact"] as const,

  dashboardSummary: () => ["/api/dashboard/summary"] as const,
  dashboardGamePlan: () => ["/api/dashboard/game-plan"] as const,
  recentActivity: () => ["/api/recent-activity"] as const,

  featureFlags: (key: string) => ["/api/feature-flags", key] as const,
  aiNudges: () => ["/api/ai/nudges"] as const,
  aiNudgesDaily: () => ["/api/ai/nudges", "daily"] as const,
  aiImpact: () => ["/api/ai/impact"] as const,
  aiBookingInsights: () => ["/api/ai/booking-insights"] as const,
  outcomes: () => ["/api/outcomes"] as const,

  clientInfo: (phone: string | null | undefined, email: string | null | undefined) => ["/api/client", phone, email] as const,
  drivingDistance: (pLat: number, pLng: number, cLat: number, cLng: number) => ["/api/driving-distance", pLat, pLng, cLat, cLng] as const,

  stripeConnectStatus: () => ["/api/stripe/connect/status"] as const,

  publicCrewPortal: (token: string) => ["/api/public/crew-portal", token] as const,
  publicProfile: (slug: string) => ["/api/public/profile", slug] as const,
  publicAvailableSlots: (slug: string, date: string) => ["/api/public/available-slots", slug, date] as const,
  publicSmartSlots: (slug: string, date: string, zip: string) => ["/api/public/smart-slots", slug, date, zip] as const,

  adminStatus: () => ["/api/admin/status"] as const,
  adminSystem: () => ["/api/admin/system"] as const,
  adminTestSummary: () => ["/api/admin/test-summary"] as const,
  adminCockpitSummary: () => ["/api/admin/cockpit/summary"] as const,
  adminCockpitFocus: () => ["/api/admin/cockpit/focus"] as const,
  adminCockpitAlerts: () => ["/api/admin/cockpit/alerts"] as const,
  adminCockpitRiskLeakage: () => ["/api/admin/cockpit/risk-leakage"] as const,
  adminCockpitRevenuePayments: () => ["/api/admin/cockpit/revenue-payments"] as const,
  adminCockpitActivationFunnel: () => ["/api/admin/cockpit/activation-funnel"] as const,
  adminUser: (userId: string) => ["/api/admin/users", userId] as const,
  adminUserTimeline: (userId: string) => ["/api/admin/users", userId, "timeline"] as const,
  adminUserAudit: (userId: string) => ["/api/admin/users", userId, "audit"] as const,
  adminUserMessaging: (userId: string) => ["/api/admin/users", userId, "messaging"] as const,
  adminUserSmsRateLimit: (userId: string) => ["/api/admin/users", userId, "sms-rate-limit"] as const,
  adminUserPayments: (userId: string) => ["/api/admin/users", userId, "payments"] as const,
  adminExternalLinks: () => ["/api/admin/users/links/external"] as const,
  adminUsers: () => ["/api/admin/users"] as const,
  adminUsersPlanPrices: () => ["/api/admin/users/plan-prices"] as const,
  adminAuditLogs: () => ["/api/admin/audit-logs"] as const,
  adminAnalytics: () => ["/api/admin/analytics"] as const,
  adminAnalyticsGrowth: () => ["/api/admin/analytics/growth"] as const,
  adminBilling: () => ["/api/admin/billing"] as const,
  adminBillingRevenue: () => ["/api/admin/billing/revenue"] as const,
  adminBillingMetrics: () => ["/api/admin/billing/metrics"] as const,
  adminStripeStats: () => ["/api/admin/stripe/stats"] as const,
  adminStripeWebhooks: () => ["/api/admin/stripe/webhooks"] as const,
  adminStripePayments: () => ["/api/admin/stripe/payments"] as const,
  adminStripeDisputes: () => ["/api/admin/stripe/disputes"] as const,
  adminCustomerioStatus: () => ["/api/admin/customerio/status"] as const,
  adminCustomerioCampaigns: () => ["/api/admin/customerio/campaigns"] as const,
  adminCustomerioDelivery: () => ["/api/admin/customerio/delivery-metrics"] as const,
  invoicePayments: (id: string | number) => [`/api/invoices/${id}/payments`] as const,

  eligibleClients: (channel: string) => ["/api/notification-campaigns/eligible-clients", channel] as const,
  adminSystemStatus: () => ["/api/admin/system/status"] as const,
  adminSmsHealthSummary: () => ["/api/admin/sms/summary"] as const,
  adminSmsOptOuts: (queryParams?: string) =>
    queryParams
      ? ([`/api/admin/sms/opt-outs?${queryParams}`] as const)
      : (["/api/admin/sms/opt-outs"] as const),
  adminSmsOptOutEvents: () => ["/api/admin/sms/opt-out-events"] as const,
  adminSmsDuplicatePhones: () => ["/api/admin/sms/duplicate-phones"] as const,
  adminSmsClearPhoneAudit: (queryParams?: string) =>
    queryParams
      ? ([`/api/admin/sms/clear-phone-audit?${queryParams}`] as const)
      : (["/api/admin/sms/clear-phone-audit"] as const),
  adminUserOutboundMessages: (userId: string) => ["/api/admin/users", userId, "outbound-messages"] as const,
  adminUserSmsOptOutEvents: (userId: string) => ["/api/admin/users", userId, "sms-opt-out-events"] as const,
  adminSystemJobs: () => ["/api/admin/system/jobs"] as const,
  adminSystemErrors: () => ["/api/admin/system/errors"] as const,
  adminAnalyticsCohorts: () => ["/api/admin/analytics/cohorts"] as const,
  adminAnalyticsLtv: () => ["/api/admin/analytics/ltv"] as const,
  adminAnalyticsRevenue: () => ["/api/admin/analytics/revenue"] as const,
  adminAuditLogActionKeys: () => ["/api/admin/audit-logs/action-keys"] as const,
  adminUsersSearch: (query: string) => ["/api/admin/users/search", query] as const,
  adminUsersViews: (view: string, page: number | string) => ["/api/admin/users/views", view, page] as const,
  downloads: () => ["/api/downloads"] as const,
  voiceNotes: () => ["/api/voice-notes"] as const,
  supportTickets: () => ["/api/support/tickets"] as const,
  ownerMetrics: () => ["/api/owner/metrics"] as const,
  publicQuickbook: (token: string) => ["/api/public/quickbook", token] as const,
  publicDeposit: (token: string) => ["/api/public/deposit", token] as const,
  publicPriceConfirmation: (token: string) => ["/api/public/price-confirmation", token] as const,
  publicInvoice: (token: string) => ["/api/public/invoice", token] as const,
  automationSettings: () => ["/api/automation-settings"] as const,
  emailSignature: () => ["/api/user/email-signature"] as const,
  adminAuditLogsQuery: (queryParams: string) => [`/api/admin/audit-logs?${queryParams}`] as const,
  adminAnalyticsFunnels: (days: number | string) => [`/api/admin/analytics/funnels?days=${days}`] as const,
  adminAnalyticsShareFunnel: (days: number | string) => [`/api/admin/analytics/share-funnel?days=${days}`] as const,
  adminAnalyticsFirstBookingEmails: (days: number | string) => [`/api/admin/analytics/first-booking-emails?days=${days}`] as const,
  publicReview: (token: string) => [`/api/public/review/${token}`] as const,

  jobTemplates: () => ["/api/job-templates"] as const,
  followUpRules: () => ["/api/follow-up-rules"] as const,
  followUpLogs: () => ["/api/follow-up-logs"] as const,
  rebookingRules: () => ["/api/rebooking-rules"] as const,
  rebookingLogs: () => ["/api/rebooking-logs"] as const,
  moneyDashboard: () => ["/api/money-dashboard"] as const,
  quoteEstimate: () => ["/api/quote-estimate"] as const,
  priceOptimization: () => ["/api/price-optimization"] as const,
  priceAdjustments: () => ["/api/price-adjustments"] as const,
  profitWarnings: () => ["/api/profit-warnings"] as const,

  adminChurnOverview: () => ["/api/admin/churn/overview"] as const,
  adminChurnUsers: (params?: string) => ["/api/admin/churn/users", params || ""] as const,
  adminChurnUser: (userId: string) => ["/api/admin/churn/user", userId] as const,
  adminChurnPlaybooks: () => ["/api/admin/churn/playbooks"] as const,
  adminChurnReport: () => ["/api/admin/churn/report.json"] as const,

  encouragementData: () => ["/api/encouragement/data"] as const,

  adminGrowthOverview: (days: number) => ["/api/admin/growth/overview", `days=${days}`] as const,
  adminGrowthLeads: () => ["/api/admin/growth/leads"] as const,
  adminGrowthOutreach: () => ["/api/admin/growth/outreach"] as const,
  adminGrowthChannels: () => ["/api/admin/growth/channels"] as const,
  adminFirstBookingFunnel: (window: string, source: string, location: string) =>
    ["/api/admin/analytics/first-booking-funnel", window, source, location] as const,
  adminFirstBookingFunnelPages: (window: string, source: string, location: string) =>
    ["/api/admin/analytics/first-booking-funnel/pages", window, source, location] as const,
  adminFirstBookingFunnelPage: (pageId: string) => ["/api/admin/analytics/first-booking-funnel/pages", pageId, "detail"] as const,
};
